os:
  - linux
language:
  - node_js
node_js:
  - "6.10.3"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm test
# load the db
#$ mysql -t < employees.sql
# validate the db # how to validate that ? lol idk
#$ time mysql -t < test_employees_sha.sql
#$ time mysql -t < test_employees_md5.sql
